-- Tabla de estudiantes
create table public.alumnos (
  id bigint generated by default as identity not null,
  cedula text not null unique,
  apellidos text not null,
  nombres text not null,
  paralelo text not null,
  contrasena_hash text not null,
  created_at timestamp with time zone null default now(),
  constraint alumnos_pkey primary key (id)
);

-- Tabla de entregas de proyectos
create table public.entregas_tareas (
  id bigint generated always as identity not null,
  alumno_id bigint null,
  codigo_html text null,
  codigo_css text null,
  codigo_js text null,
  estado text null default 'POR REVISAR',
  observaciones text null,
  updated_at timestamp with time zone null default now(),
  constraint entregas_tareas_pkey primary key (id),
  constraint entregas_tareas_alumno_id_fkey foreign KEY (alumno_id) references alumnos (id)
);

-- Tabla de configuración (código de registro docente)
create table public.configuracion (
  clave text primary key,
  valor text not null
);

insert into public.configuracion (clave, valor)
values ('codigo_registro_docente', 'Albertina2026')
on conflict (clave) do nothing;
